name: DracoPanel Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bağımlılıkları yükle
        run: |
          pip install -r requirements.txt  # Eğer requirements.txt varsa

      - name: Otomasyon testlerini çalıştır
        run: python main.py
